/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnnouncementList: typeof import('./../../components/home/announcement-list/index.vue')['default']
    Aside: typeof import('./../../components/admin/aside/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    FeatureCards: typeof import('./../../components/home/feature-cards/index.vue')['default']
    Footer: typeof import('./../../components/main/footer/index.vue')['default']
    Header: typeof import('./../../components/admin/header/index.vue')['default']
    HeroSection: typeof import('./../../components/home/hero-section/index.vue')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpBack: typeof import('~icons/ep/back')['default']
    IEpBell: typeof import('~icons/ep/bell')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpGoldMedal: typeof import('~icons/ep/gold-medal')['default']
    IEpList: typeof import('~icons/ep/list')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpMedal: typeof import('~icons/ep/medal')['default']
    IEpOperation: typeof import('~icons/ep/operation')['default']
    IEpReading: typeof import('~icons/ep/reading')['default']
    IEpSchool: typeof import('~icons/ep/school')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    IEpSwitchButton: typeof import('~icons/ep/switch-button')['default']
    IEpTrophy: typeof import('~icons/ep/trophy')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    OjCol: typeof import('./../../components/grid/OjCol.vue')['default']
    OjRow: typeof import('./../../components/grid/OjRow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./../../components/main/header/components/them-toggle.vue')['default']
    UserDropdown: typeof import('./../../components/main/header/components/user-dropdown.vue')['default']
  }
}
