/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./../../components/admin/aside/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    Footer: typeof import('./../../components/main/footer/index.vue')['default']
    Header: typeof import('./../../components/admin/header/index.vue')['default']
    IEpArrowDown: typeof import('~icons/ep/arrow-down')['default']
    IEpBack: typeof import('~icons/ep/back')['default']
    IEpBell: typeof import('~icons/ep/bell')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpList: typeof import('~icons/ep/list')['default']
    IEpMedal: typeof import('~icons/ep/medal')['default']
    IEpOperation: typeof import('~icons/ep/operation')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    IEpSwitchButton: typeof import('~icons/ep/switch-button')['default']
    IEpTrophy: typeof import('~icons/ep/trophy')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    OjCol: typeof import('./../../components/grid/OjCol.vue')['default']
    OjRow: typeof import('./../../components/grid/OjRow.vue')['default']
    RankingBoard: typeof import('./../../components/RankingBoard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemToggle: typeof import('./../../components/main/header/components/them-toggle.vue')['default']
    UserDropdown: typeof import('./../../components/main/header/components/user-dropdown.vue')['default']
  }
}
